### ISSUE TITLE
[Feature request] FastContext constructor taking an InputStream instead of a path as a String

### ISSUE THREAD

**Issue by twktheainur** [jianlins/FastContext#1]
Currently one can either provide a string with the path of the rule file (.tsv by ferault) to load or an existing list of rules that were already parsed from a file. 
This does not allow to load a this .tsv to be loaded from a resource packaged in a jar file (e.g. a servlet deployed on an application server), short of reading the file through a stream an creating a temporary file with the contents, which is clearly sub-optimal. 

Could the loading mechanism be refactored to also take an InputStream rather than just a path?

**Comment by jianlins** [comment]
Thanks for the suggestion. I didn't expect the rule file to be packed within a jar. Because external files can be easily modified overtime. But supporting inputsteam is a good point, just updated. Thanks
