### ISSUE TITLE
Syntax specification for the textual rule file

### ISSUE THREAD

**Issue by twktheainur** [jianlins/FastContext#2]
We are trying to adapt existing trigger terms in another language from the format of the original java implementation of ConText to the format of FastConText. While most of the syntax can be extrapolated trivially, some elements require some clarification: 
   - Does \w+ mean one or more words? 
   - What is the syntax for the temporarily triggers ? In particular: \> and - 
      Does the \> always go before the numerical value? Could I have a trigger term such that \> is in the middle? e.g. : "il y a \> 1 semaine|backward|trigger|historical|30"? Am I inferring the syntax improperly?

**Comment by jianlins** [comment]
\w+ means one token. Depending on how your tokenizer works, it can include word, punctuation, etc.

For the 2nd question, do you mean the test2() in https://github.com/jianlins/FastContext/blob/master/src/test/java/edu/utah/bmi/nlp/fastcontext/TestFastContextAPIs2.java?
