### ISSUE TITLE
Command line interface

### ISSUE THREAD

**Issue by PabloBotas** [jianlins/FastContext#3]
I would like to use this software, but don't know how to create a stand alone package to be used from a command line environment.

How could this be achieved?

Thanks!

**Comment by jianlins** [comment]
Sure. You will need to write your own main class to take the input and export the output, and then package it up into a jar file, so that you can call it from the command line.
https://www.baeldung.com/executable-jar-with-maven

**Comment by PabloBotas** [comment]
Ok, thanks!
Would you interested in a PR for this feature? If so, any preference that you think will fit better with the overall design of FastContext? (I've never used Java before, so if you'd provide some guidance, I'd you'd make me very happy)

**Comment by jianlins** [comment]
It is not easy to write a general commandline program to accomplish diversed tasks. If you don't have any java program experience, please take a look at this instead.
https://github.com/jianlins/EasyCIE_GUI
